### ISSUE TITLE
kubectl. can you guys help me?

### ISSUE THREAD

**Issue by zarifeyeman** [Calinou/0x0#4] opened 2022-02-03 05:58 UTC
/usr/local/bin/kubectl: line 1: syntax error near unexpected token `newline'

/usr/local/bin/kubectl: line 1: '<!doctype html>'

**Comment by Calinou** [comment] 2022-02-03 17:53
Duplicate of https://github.com/Calinou/0x0/issues/3.

**Closed as completed by Calinou** 2022-02-03 17:53 UTC
Labels: bug, invalid
